name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build (channel=${{ matrix.channel }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-16.04', 'macos-10.15']
        channel: ['stable', 'beta']
        # features: ['', '--features=asm']
    steps:
      - uses: actions/checkout@v1
      - run: ./test.sh
        env:
          CHANNEL: ${{ matrix.channel }}
          FEATURES: ${{ matrix.features }}
