name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build (os=${{ matrix.os }}, channel=${{ matrix.channel }}, features=${{ matrix.features }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-11']
        channel: ['stable', 'beta']
        features: ['', '--features=asm']
    steps:
      - uses: actions/checkout@v1
      - run: ./test.sh
        env:
          CHANNEL: ${{ matrix.channel }}
          FEATURES: ${{ matrix.features }}
